spring:  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market_db?serverTimezone=Europe/Moscow
    username: root
    password: 123
    properties:
      hybernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
